services:
  laporaa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laporaa-be
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - laporaa-network

  db:
    image: mongo:8
    container_name: laporaa-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=5V0LVmc33zXj
      - MONGO_INITDB_DATABASE=laporaa-db
    volumes:
      - mongolaporaadata:/data/db
    restart: unless-stopped
    networks:
      - laporaa-network

volumes:
  mongolaporaadata:

networks:
  laporaa-network:
    driver: bridge